# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7001cc4003da2848781aec9452fbd5a08fd266877a1f9a5824bc11b4bca3d03cca464395fdb5b4b7a03d49eecb0e8a76be3be16d5ce4b4860788c4a6d5c7eb1f

test:
  secret_key_base: 01d9c9d85cd88bffcaeef35a38aa341c062b2f1e65bd898272955b78bd79e154a1e00d636d91ee9a699f40ed7d5a95196fde930d1d730baca331ad9f9078a68c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
